// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ythklqwdlovpreqeybtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aGtscXdkbG92cHJlcWV5YnR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4NzQzNzcsImV4cCI6MjA1NDQ1MDM3N30.Jt2RAFteiv245oQ45UW8kmcy1kLVN-kIkDBI-Av5ddQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);